### ISSUE TITLE
update mac install instructions in readme

### ISSUE THREAD

**Issue by chris-s-friedman** [cool-RR/git-recent#1]
I spent a day or two trying to install this on my machine. After `curl`ing it onto a location on my path, reloading my `.zshrc`, restarting my shell , I still couldn't get it to work. Andthen this morning I realized, I needed to run `chmod -x ~/bin/git-recent`. After doing that it works!

Maybe we can add some mac specific documentation to the installation instructions in the readme?

This is great little tool, by the way! Thanks for putting it together! I can branch and make a PR to the readme, if you'd like!

**Comment by cool-RR** [comment]
Ah dang, I didn't think about that. Yes, I'd like that PR, thank you!

**Comment by chris-s-friedman** [comment]
Closed by #2 

Thanks again for putting this together, @cool-RR !
